name: Analisar Arquivos
description: Analisa se há arquivos python no repo

inputs:
  repository-to-checkout:
    description: 'Nome do repositório a ser clonado'
    required: true
  repository-ref:
    description: 'branch a ser analisada'
    required: true

runs:  
  using: "composite"
  steps:
    - name: Verificar versão do Python
      run: python --version
      shell: bash
