name: Analisar Arquivos
description: Analisa se há arquivos python no repo

inputs:
  repository-to-checkout:
    description: 'Nome do repositório a ser clonado'
    required: true
  repository-ref:
    description: 'branch a ser analisada'
    required: true

runs:  
  using: "composite"
  steps:
    - name: Verificar versão do Python
      run: python --version
      shell: bash

    - name: Checkout do código
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repository-to-checkout }}
        ref: ${{ github.event.inputs.repository-ref }}
        path: repository-to-analyze

    - name: Executar script Python de Análise
      run: python repository-to-analyze/script_de_analise.py repository-to-analyze
      shell: bash
